import { beforeEach, expect, test } from "bun:test";
import { eq, sql } from "drizzle-orm";
import { db } from "../../db/client.ts";
import { clients, invoiceItems, invoiceSequences, invoices } from "../../db/schema.ts";
import { operationIdentity } from "../../domain/invoice-workspace.ts";
import { createInvoice, getInvoiceDetail } from "./invoices.service.ts";
import { deleteDraftInvoiceCommand, operationResult } from "./invoice-workspace.service.ts";

beforeEach(()=>{db.delete(invoiceItems).run();db.delete(invoices).run();db.delete(invoiceSequences).run();db.delete(clients).run();});
function fixture(){const now="2026-09-09T00:00:00.000Z",client=db.insert(clients).values({name:"Delete",code:`D${crypto.randomUUID().slice(0,8)}`,defaultCurrency:"GBP",numberingProfileId:1,createdAt:now,updatedAt:now}).returning().get(),invoice=createInvoice({clientId:client.id,invoiceDate:"2026-09-09",currency:"GBP",items:[{name:"x",value:"1.00",source:"other"}]});return getInvoiceDetail(invoice.id)!;}
function command(id:number,revision:number,key=crypto.randomUUID()){const raw={schemaVersion:1 as const,operationId:key,expectedRevision:revision,kind:"delete" as const,arguments:{}};return{...raw,canonicalPayloadDigest:operationIdentity({schemaVersion:1,kind:"delete",baseRevision:revision,arguments:{}})};}
test("draft deletion is replayable after physical deletion and rejects stale/non-draft/key mismatch",()=>{const detail=fixture(),input=command(detail.invoice.id,detail.invoice.workspaceRevision);expect(deleteDraftInvoiceCommand(detail.invoice.id,input)).toMatchObject({outcome:"committed"});expect(deleteDraftInvoiceCommand(detail.invoice.id,input)).toMatchObject({outcome:"committed"});expect(operationResult(detail.invoice.id,input.operationId)).toMatchObject({outcome:"committed"});try{deleteDraftInvoiceCommand(detail.invoice.id,{...input,canonicalPayloadDigest:"a".repeat(64)});}catch(error){expect((error as any).code).toBe("OPERATION_KEY_REUSED");}const stale=fixture();expect(deleteDraftInvoiceCommand(stale.invoice.id,command(stale.invoice.id,99))).toMatchObject({outcome:"rejected",code:"STALE_REVISION"});const locked=fixture();db.update(invoices).set({status:"issued"}).where(eq(invoices.id,locked.invoice.id)).run();expect(deleteDraftInvoiceCommand(locked.invoice.id,command(locked.invoice.id,locked.invoice.workspaceRevision))).toMatchObject({outcome:"rejected",code:"INVALID_STATUS"});});
test("a failed receipt insert rolls back deletion",()=>{const detail=fixture(),input=command(detail.invoice.id,detail.invoice.workspaceRevision);db.run(sql.raw("CREATE TRIGGER abort_delete_receipt BEFORE INSERT ON invoice_deletion_receipts BEGIN SELECT RAISE(ABORT, 'no receipt'); END;"));try{expect(()=>deleteDraftInvoiceCommand(detail.invoice.id,input)).toThrow("no receipt");expect(getInvoiceDetail(detail.invoice.id)).not.toBeNull();}finally{db.run(sql.raw("DROP TRIGGER abort_delete_receipt"));}});
