/**
 * Generates a manifest of runtime files that Bun should embed in the compiled
 * executable. The app extracts these files at startup so existing filesystem
 * consumers (Hono static files and Drizzle migrations) keep working.
 */
import { readdir, writeFile } from "node:fs/promises";
import { join, relative, sep } from "node:path";

const ROOT = join(import.meta.dir, "..");
const OUTFILE = join(ROOT, "src", "runtime", "embedded-files.generated.ts");

const RUNTIME_DIRS = ["src/public", "drizzle"];

async function listFiles(dir: string): Promise<string[]> {
  const entries = await readdir(join(ROOT, dir), { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) return listFiles(path);
      if (entry.isFile()) return [path];
      return [];
    }),
  );
  return files.flat();
}

function posixPath(path: string): string {
  return path.split(sep).join("/");
}

const files = (await Promise.all(RUNTIME_DIRS.map(listFiles))).flat().sort();

const lines = [
  "// @ts-nocheck",
  "/* This file is generated by scripts/generate-embedded-runtime.ts. */",
  "",
];

files.forEach((file, index) => {
  const importPath = posixPath(relative(join(ROOT, "src", "runtime"), join(ROOT, file)));
  const normalizedImportPath = importPath.startsWith(".") ? importPath : `./${importPath}`;
  lines.push(`import file${index} from ${JSON.stringify(normalizedImportPath)} with { type: "file" };`);
});

lines.push("", "export const embeddedRuntimeFiles = [");
files.forEach((file, index) => {
  lines.push(`  { source: file${index}, target: ${JSON.stringify(posixPath(file))} },`);
});
lines.push("] as const;", "");

await writeFile(OUTFILE, lines.join("\n"));
console.log(`embedded runtime manifest generated with ${files.length} files`);
